### ISSUE TITLE
Suggestion- example of reactQL+react storybook

### ISSUE THREAD

**Issue by CaptainChemist** [reactql/examples#6]
This is definitely an enhancement, but it would be incredibly helpful if there was documentation for how to add react storybook to reactQL. When I add storybook to the project using `getstorybook` from the command line, it creates a new folder called `.storybook` that has a config file in it as well as a `webpack.config.js` file in it. 

Storybook claims that it will use the root `webpack.config.js` and `.babelrc` file, but when I launch storybook it gives an error on the `<` bracket in a react component, which suggests to me that I am not properly importing the webpack configs into storybook. 

Has anyone gotten this to work successfully? Thanks again for this amazing reactQL, it is the best boilerplate I have ever seen hands down.

**Comment by leebenson** [comment]
This might be a tricky one, @CaptainChemist. I've used Storybook in past projects and managed to get custom Webpack settings to work, but only by mutating what already existed, and not replacing the entire Webpack chain.

Since ReactQL puts Webpack front and centre in its build chain, it would (probably) mean lots of fiddly work to avoid Webpack clashes.

I'll go ahead and close this, only because it's not a testing environment that I typically use myself and I don't personally have the cycles currently to explore this further. I remain open to PRs from the community though, of course. Thanks for suggesting this @CaptainChemist.
